<?php echo $this->pageTitle($this->translate('Site Statistics')); ?>

<style>
    .table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 10px;
        font-family: Arial, sans-serif;
    }

    .table th, .table td {
        border: 1px solid #ddd;
        padding: 4px;
        text-align: left;
    }

    .table th {
        background-color: #404e61;
        color: white;
        font-weight: bold;
    }

    .table-striped tbody tr:nth-of-type(odd) {
        background-color: #f9f9f9;
    }

    .table-striped tbody tr:nth-of-type(even) {
        background-color: #bdcde3;
    }

    .table-striped tbody tr:hover {
        background-color: #d3e7ff;
    }

    .statistics h2, .sites h2, .modules h2 {
        color: #404e61;
        margin-bottom: 20px;
    }

    .custom-btn {
        padding: 10px 20px;
        border: 2px solid transparent;
        color: white;
        cursor: pointer;
        font-size: 16px;
        border-radius: 30px;
        transition: all 0.3s ease;
        display: inline-block;
        min-width: 120px;
        text-align: center;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    }

    /* .primary-btn {
        background-color: #404e61;
        border-color: #404e61;
    }

    .primary-btn:hover {
        background-color: #56607a;
        border-color: #56607a;
    } */

    .success-btn {
        background-color: #28a745;
        border-color: #28a745;
    }

    .success-btn:hover {
        background-color: #45b564;
        border-color: #45b564;
    }

    .danger-btn {
        background-color: #dc3545;
        border-color: #dc3545;
    }

    .danger-btn:hover {
        background-color: #e35b6b;
        border-color: #e35b6b;
    }

    .yellow-btn {
        background-color: #ffc107;
        border-color: #ffc107;
        color: #fff;
    }

    .yellow-btn:hover {
        background-color: #ffca2c;
        border-color: #ffca2c;
    }

    .custom-btn:hover {
        transform: translateY(-3px);
        box-shadow: 0 8px 12px rgba(0, 0, 0, 0.2);
    }

    .custom-btn:active {
        transform: translateY(0);
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    }

    
    .chart-container {
        width: 70%;
        margin: auto;
        height: 20%;
    }
    .btn-lien {
    width: 30px;
    height: 30px;
    background-color: #fff;
    color: #404e61; 
    border: 2px solid #ddd;
    border-radius: 3px;
    text-align: center;
    display: inline-flex;
    justify-content: center;
    align-items: center;
    font-size: 12px;
    cursor: pointer;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    transition: all 0.3s ease;
}

.btn-lien:hover {
    background-color: #f0f0f0;
    transform: translateY(-2px);
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
}

.btn-lien:active {
    transform: translateY(0); 
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

</style>

<div class="statistics">
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th><?php echo $this->translate('Ressources'); ?></th>
                <th><?php echo $this->translate('Value'); ?></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><?php echo $this->translate('Total Items'); ?></td>
                <td>
                    <a href="<?php echo $this->basePath(); ?>/admin/item">
                        <button class="btn-lien" >
                            <?php echo $this->escapeHtml($stats['totalItems']); ?>
                        </button>
                    </a>
                </td>
            </tr>
            <tr>
                <td><?php echo $this->translate('Total ItemSets'); ?></td>
                <td>
                    <a href="<?php echo $this->basePath(); ?>/admin/item-set">
                        <button class="btn-lien">
                            <?php echo $this->escapeHtml($stats['totalItemSets']); ?>
                        </button>
                    </a>
                </td>
            </tr>
            <tr>
                <td><?php echo $this->translate('Total Users'); ?></td>
                <td>
                    <a href="<?php echo $this->basePath(); ?>/admin/user">
                        <button class="btn-lien">
                            <?php echo $this->escapeHtml($stats['totalUsers']); ?>
                        </button>
                    </a>
                </td>
            </tr>
            <tr>
                <td><?php echo $this->translate('Total Medias'); ?></td>
                <td>
                    <a href="<?php echo $this->basePath(); ?>/admin/media">
                        <button class="btn-lien">
                            <?php echo $this->escapeHtml($stats['totalMedia']); ?>
                        </button>
                    </a>
                </td>
            </tr>
            <tr>
                <td><?php echo $this->translate('Total Vocabularies'); ?></td>
                <td>
                    <a href="<?php echo $this->basePath(); ?>/admin/vocabulary">
                        <button class="btn-lien">
                            <?php echo $this->escapeHtml($stats['totalVocabularies']); ?>
                        </button>
                    </a>
                </td>
            </tr>
            <tr>
                <td><?php echo $this->translate('Total Resource Templates'); ?></td>
                <td>
                    <a href="<?php echo $this->basePath(); ?>/admin/resource-template">
                        <button class="btn-lien">
                            <?php echo $this->escapeHtml($stats['totalResourceTemplates']); ?>
                        </button>
                    </a>
                </td>
            </tr>
            <tr>
                <td><?php echo $this->translate('Total Omeka Size'); ?></td>
                <td><?php echo $this->escapeHtml($stats['totalOmekaSize']); ?></td>
            </tr>
        </tbody>
    </table>
</div>

<div class="sites">
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th><?php echo $this->escapeHtml('Site Title'); ?></th>
                <th><?php echo $this->escapeHtml('Items'); ?></th>
                <th><?php echo $this->escapeHtml('Item Sets'); ?></th>
                <th><?php echo $this->escapeHtml('Media'); ?></th>
                <th><?php echo $this->escapeHtml('Volume Media (MB)'); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($sites as $siteStat): ?>
                <tr>
                    <td><?php echo $this->escapeHtml($siteStat['site']->getTitle()); ?></td>
                    <td><?php echo $this->escapeHtml($siteStat['totalItems']); ?></td>
                    <td><?php echo $this->escapeHtml($siteStat['totalItemSets']); ?></td>
                    <td><?php echo $this->escapeHtml($siteStat['totalMedia']); ?></td>
                    <td><?php echo $this->escapeHtml($siteStat['totalMediaSize']); ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="modules">
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th><?php echo $this->translate('Modules'); ?></th>
                <th><?php echo $this->translate('Count'); ?></th>
            </tr>
        </thead>
        <tbody>
            <!-- <tr>
                <td><php echo $this->translate('Total Modules'); ?></td>
                <td>
                    <a href="<php echo $this->basePath(); ?>/admin/module">
                        <button class="custom-btn primary-btn">
                            <php echo $this->escapeHtml($modules['totalModules']); ?>
                        </button>
                    </a>
                </td>
            </tr> -->
            <tr>
                <td><?php echo $this->translate('Installed Modules'); ?></td>
                <td>
                    <a href="<?php echo $this->basePath(); ?>/admin/module">
                        <button class="custom-btn yellow-btn">
                            <?php echo $this->escapeHtml($modules['installedModules']); ?>
                        </button>
                    </a>
                </td>
            </tr>
            <tr>
                <td><?php echo $this->translate('Enabled Modules'); ?></td>
                <td>
                    <a href="<?php echo $this->basePath(); ?>/admin/module?state=active">
                        <button class="custom-btn success-btn">
                            <?php echo $this->escapeHtml($modules['enabledModules']); ?>
                        </button>
                    </a>
                </td>
            </tr>
            <tr>
                <td><?php echo $this->translate('Disabled Modules'); ?></td>
                <td>
                    <a href="<?php echo $this->basePath(); ?>/admin/module?state=not_active">
                        <button class="custom-btn danger-btn">
                            <?php echo $this->escapeHtml($modules['disabledModules']); ?>
                        </button>
                    </a>
                </td>
            </tr>
        </tbody>
    </table>
</div>

